[package]
name = "solaredge-test"
version = "0.1.0"
edition = "2018"
publish = false

[dev-dependencies]
chrono = "0.4"
env_logger = "0.9"
tokio-test = "0.4"
solaredge = { path = "../solaredge" }
solaredge-reqwest = { path = "../solaredge-reqwest" }
